import * as YAML from "yamljs";

export function renderAsYAML(object: any, includeCommentBlock: boolean): string {
  return includeCommentBlock
    ? `${generateYAMLCommentBlock()}${renderConfiguration(object)}`
    : renderConfiguration(object);
}

function renderConfiguration(object: any): string {
  return YAML.stringify(object, 10, 2);
}

function generateYAMLCommentBlock(): string {
  return `# This configuration was generated by
# \`eslint-takeoff\`
#
# on ${new Date().toISOString()}.
#
# It contains all the known ESLint errors/warnings, and prevents them from
# showing up as errors until devs can remove them from the code base.
# Remove specific errors or entire file entries as you fix the offences.

`;
}
